RM= rm -f
# Si le système est Windows, utilisez "del" pour supprimer les fichiers
ifeq ($(OS),Windows_NT)
    RM = del /q
endif

prog : main.o player.o
	gcc -o prog main.o player.o

main.o : main.c
	gcc -o main.o -c main.c -Wall

player.o : player.c
	gcc -o player.o -c player.c -Wall

clean :
	$(RM) main.o player.o